default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: bookstore_app
  password: 123456

development:
  <<: *default
  database: bookstore_app_development

test: &test
  <<: *default
  database: bookstore_app_test

production:
  <<: *default
  database: bookstore_app_production
  username: bookstore_app
  password: <%= ENV['BOOKSTORE_DATABASE_PASSWORD'] %>